staging:
  base_url: "https://dev-llm-proxy.nebulablock.com/v1/chat/completions"
  image_base_url: "https://dev-portal-api.nebulablock.com/api/v1/images/generation"
  embedding_base_url: "https://dev-llm-proxy.nebulablock.com/v1/embeddings"

production:
  base_url: "https://inference.nebulablock.com/v1/chat/completions"
  image_base_url: "https://api.nebulablock.com/api/v1/images/generation"
  embedding_base_url: "https://inference.nebulablock.com/v1/embeddings" 